import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NDKProvider } from "@/hooks/useNDK";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create nostr App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NDKProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </NDKProvider>
  );
}
