import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NDKProvider } from "@/hooks/useNDK";
import ResponsiveAppBar from "@/components/NavBar/NavBar";
import { Box, ThemeProvider } from "@mui/material";
import theme from "@/utils/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create nostr App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NDKProvider>
      <html lang="en">
        <body className={inter.className}>
            <ThemeProvider theme={theme}>
                <ResponsiveAppBar />
                <Box
                    display={"flex"}
                    flexDirection={"column"}
                    minHeight={"100vh"}
                >
                    <Box flexGrow={1}>
                        {children}
                    </Box>
                </Box>
            </ThemeProvider>
        </body>
      </html>
    </NDKProvider>
  );
}
